opcode_nop         equ 0x00
opcode_ld_bc_nnnn  equ 0x01
opcode_ld_mbc_a    equ 0x02
opcode_inc_bc      equ 0x03
opcode_inc_b       equ 0x04
opcode_dec_b       equ 0x05
opcode_ld_b_nn     equ 0x06
opcode_rlca        equ 0x07
opcode_ex_af_af    equ 0x08
opcode_add_hl_bc   equ 0x09
opcode_ld_a_mbc    equ 0x0A
opcode_dec_bc      equ 0x0B
opcode_inc_c       equ 0x0C
opcode_dec_c       equ 0x0D
opcode_ld_c_nn     equ 0x0E
opcode_rrca        equ 0x0F
opcode_djnz        equ 0x10
opcode_ld_de_nnnn  equ 0x11
opcode_ld_mde_a    equ 0x12
opcode_inc_de      equ 0x13
opcode_inc_d       equ 0x14
opcode_dec_d       equ 0x15
opcode_ld_d_nn     equ 0x16
opcode_rla         equ 0x17
opcode_jr          equ 0x18
opcode_add_hl_de   equ 0x19
opcode_ld_a_mde    equ 0x1A
opcode_dec_de      equ 0x1B
opcode_inc_e       equ 0x1C
opcode_dec_e       equ 0x1D
opcode_ld_e_nn     equ 0x1E
opcode_rra         equ 0x1F
opcode_jr_nz       equ 0x20
opcode_ld_hl_nnnn  equ 0x21
opcode_ld_mnnnn_hl equ 0x22
opcode_inc_hl      equ 0x23
opcode_inc_h       equ 0x24
opcode_dec_h       equ 0x25
opcode_ld_h_nn     equ 0x26
opcode_daa         equ 0x27
opcode_jr_z        equ 0x28
opcode_add_hl_hl   equ 0x29
opcode_ld_hl_mnnnn equ 0x2A
opcode_dec_hl      equ 0x2B
opcode_inc_l       equ 0x2C
opcode_dec_l       equ 0x2D
opcode_ld_l_nn     equ 0x2E
opcode_cpl         equ 0x2F
opcode_jr_nc       equ 0x30
opcode_ld_sp_nn    equ 0x31
opcode_ld_mnnnn_a  equ 0x32
opcode_inc_sp      equ 0x33
opcode_inc_mhl     equ 0x34
opcode_dec_mhl     equ 0x35
opcode_ld_mhl_nn   equ 0x36
opcode_scf         equ 0x37
opcode_jr_c        equ 0x38
opcode_add_hl_sp   equ 0x39
opcode_ld_a_mnnnn  equ 0x3A
opcode_dec_sp      equ 0x3B
opcode_inc_a       equ 0x3C
opcode_dec_a       equ 0x3D
opcode_ld_a_nn     equ 0x3E
opcode_ccf         equ 0x3F
opcode_ld_b_b      equ 0x40
opcode_ld_b_c      equ 0x41
opcode_ld_b_d      equ 0x42
opcode_ld_b_e      equ 0x43
opcode_ld_b_h      equ 0x44
opcode_ld_b_l      equ 0x45
opcode_ld_b_mhl    equ 0x46
opcode_ld_b_a      equ 0x47
opcode_ld_c_b      equ 0x48
opcode_ld_c_c      equ 0x49
opcode_ld_c_d      equ 0x4A
opcode_ld_c_e      equ 0x4B
opcode_ld_c_h      equ 0x4C
opcode_ld_c_l      equ 0x4D
opcode_ld_c_mhl    equ 0x4E
opcode_ld_c_a      equ 0x4F
opcode_ld_d_b      equ 0x50
opcode_ld_d_c      equ 0x51
opcode_ld_d_d      equ 0x52
opcode_ld_d_e      equ 0x53
opcode_ld_d_h      equ 0x54
opcode_ld_d_l      equ 0x55
opcode_ld_d_mhl    equ 0x56
opcode_ld_d_a      equ 0x57
opcode_ld_e_b      equ 0x58
opcode_ld_e_c      equ 0x59
opcode_ld_e_d      equ 0x5A
opcode_ld_e_e      equ 0x5B
opcode_ld_e_h      equ 0x5C
opcode_ld_e_l      equ 0x5D
opcode_ld_e_mhl    equ 0x5E
opcode_ld_e_a      equ 0x5F
opcode_ld_h_b      equ 0x60
opcode_ld_h_c      equ 0x61
opcode_ld_h_d      equ 0x62
opcode_ld_h_e      equ 0x63
opcode_ld_h_h      equ 0x64
opcode_ld_h_l      equ 0x65
opcode_ld_h_mhl    equ 0x66
opcode_ld_h_a      equ 0x67
opcode_ld_l_b      equ 0x68
opcode_ld_l_c      equ 0x69
opcode_ld_l_d      equ 0x6A
opcode_ld_l_e      equ 0x6B
opcode_ld_l_h      equ 0x6C
opcode_ld_l_l      equ 0x6D
opcode_ld_l_mhl    equ 0x6E
opcode_ld_l_a      equ 0x6F
opcode_ld_mhl_b    equ 0x70
opcode_ld_mhl_c    equ 0x71
opcode_ld_mhl_d    equ 0x72
opcode_ld_mhl_e    equ 0x73
opcode_ld_mhl_h    equ 0x74
opcode_ld_mhl_l    equ 0x75
opcode_halt        equ 0x76
opcode_ld_mhl_a    equ 0x77
opcode_ld_a_b      equ 0x78
opcode_ld_a_c      equ 0x79
opcode_ld_a_d      equ 0x7A
opcode_ld_a_e      equ 0x7B
opcode_ld_a_h      equ 0x7C
opcode_ld_a_l      equ 0x7D
opcode_ld_a_mhl    equ 0x7E
opcode_ld_a_a      equ 0x7F
opcode_add_a_b     equ 0x80
opcode_add_a_c     equ 0x81
opcode_add_a_d     equ 0x82
opcode_add_a_e     equ 0x83
opcode_add_a_h     equ 0x84
opcode_add_a_l     equ 0x85
opcode_add_a_mhl   equ 0x86
opcode_add_a_a     equ 0x87
opcode_adc_a_b     equ 0x88
opcode_adc_a_c     equ 0x89
opcode_adc_a_d     equ 0x8A
opcode_adc_a_e     equ 0x8B
opcode_adc_a_h     equ 0x8C
opcode_adc_a_l     equ 0x8D
opcode_adc_a_mhl   equ 0x8E
opcode_adc_a_a     equ 0x8F
opcode_sub_b       equ 0x90
opcode_sub_c       equ 0x91
opcode_sub_d       equ 0x92
opcode_sub_e       equ 0x93
opcode_sub_h       equ 0x94
opcode_sub_l       equ 0x95
opcode_sub_mhl     equ 0x96
opcode_sub_a       equ 0x97
opcode_sbc_a_b     equ 0x98
opcode_sbc_a_c     equ 0x99
opcode_sbc_a_d     equ 0x9A
opcode_sbc_a_e     equ 0x9B
opcode_sbc_a_h     equ 0x9C
opcode_sbc_a_l     equ 0x9D
opcode_sbc_a_mhl   equ 0x9E
opcode_sbc_a_a     equ 0x9F
opcode_and_b       equ 0xA0
opcode_and_c       equ 0xA1
opcode_and_d       equ 0xA2
opcode_and_e       equ 0xA3
opcode_and_h       equ 0xA4
opcode_and_l       equ 0xA5
opcode_and_mhl     equ 0xA6
opcode_and_a       equ 0xA7
opcode_xor_b       equ 0xA8
opcode_xor_c       equ 0xA9
opcode_xor_d       equ 0xAA
opcode_xor_e       equ 0xAB
opcode_xor_h       equ 0xAC
opcode_xor_l       equ 0xAD
opcode_xor_mhl     equ 0xAE
opcode_xor_a       equ 0xAF
opcode_or_b        equ 0xB0
opcode_or_c        equ 0xB1
opcode_or_d        equ 0xB2
opcode_or_e        equ 0xB3
opcode_or_h        equ 0xB4
opcode_or_l        equ 0xB5
opcode_or_mhl      equ 0xB6
opcode_or_a        equ 0xB7
opcode_cp_b        equ 0xB8
opcode_cp_c        equ 0xB9
opcode_cp_d        equ 0xBA
opcode_cp_e        equ 0xBB
opcode_cp_h        equ 0xBC
opcode_cp_l        equ 0xBD
opcode_cp_mhl      equ 0xBE
opcode_cp_a        equ 0xBF
opcode_ret_nz      equ 0xC0
opcode_pop_bc      equ 0xC1
opcode_jp_nz       equ 0xC2
opcode_jp          equ 0xC3
opcode_call_nz_nn  equ 0xC4
opcode_push_bc     equ 0xC5
opcode_add_a_nn    equ 0xC6
opcode_rst_0       equ 0xC7
opcode_ret_z       equ 0xC8
opcode_ret         equ 0xC9
opcode_jp_z        equ 0xCA
opcode_rlc_b       equ 0xCB
opcode_call_z      equ 0xCC
opcode_call        equ 0xCD
opcode_adc_a_nn    equ 0xCE
opcode_rst_8       equ 0xCF
opcode_ret_nc      equ 0xD0
opcode_pop_de      equ 0xD1
opcode_jp_nc       equ 0xD2
opcode_out_mn_a    equ 0xD3
opcode_call_nc     equ 0xD4
opcode_push_de     equ 0xD5
opcode_sub_nn      equ 0xD6
opcode_rst_10      equ 0xD7
opcode_ret_c       equ 0xD8
opcode_exx         equ 0xD9
opcode_jp_c        equ 0xDA
opcode_in_a_mnn    equ 0xDB
opcode_call_c      equ 0xDC
; PREFIX #DD
opcode_sbc_a_nn    equ 0xDE
opcode_rst_18      equ 0xDF
opcode_ret_po      equ 0xE0
opcode_pop_hl      equ 0xE1
opcode_jp_po       equ 0xE2
opcode_ex_msp_hl   equ 0xE3
opcode_call_po     equ 0xE4
opcode_push_hl     equ 0xE5
opcode_and_nn      equ 0xE6
opcode_rst_20      equ 0xE7
opcode_ret_pe      equ 0xE8
opcode_jp_mhl      equ 0xE9 ; this jp (hl) syntax is wrong!
opcode_jp_hl       equ 0xE9
opcode_jp_pe       equ 0xEA
opcode_ex_de_hl    equ 0xEB
opcode_call_pe     equ 0xEC
; PREFIX #ED
opcode_xor_nn      equ 0xEE
opcode_rst_28      equ 0xEF
opcode_ret_p       equ 0xF0
opcode_pop_af      equ 0xF1
opcode_jp_p        equ 0xF2
opcode_di          equ 0xF3
opcode_call_p      equ 0xF4
opcode_push_af     equ 0xF5
opcode_or_nn       equ 0xF6
opcode_rst_30      equ 0xF7
opcode_ret_m       equ 0xF8
opcode_ld_sp_hl    equ 0xF9
opcode_jp_m        equ 0xFA
opcode_ei          equ 0xFB
opcode_call_m      equ 0xFC
; PREFIX #FD
opcode_cp_nn       equ 0xFE
opcode_rst_38      equ 0xFF
